# ComfyUI Qwen-VL Plugin
__version__ = "1.0.0"

# 导入节点类及显示名称
from .nodes.qwen3_vl_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .nodes.qwen3_vl_image_caption import NODE_CLASS_MAPPINGS as IMAGE_CAPTION_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_CAPTION_DISPLAY_MAPPINGS
from .nodes.qwen3_vl_qa import NODE_CLASS_MAPPINGS as QA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as QA_DISPLAY_MAPPINGS
from .nodes.qwen3_vl_text_generator import NODE_CLASS_MAPPINGS as TEXT_GEN_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEXT_GEN_DISPLAY_MAPPINGS
from .nodes.qwen3_vl_video_caption import NODE_CLASS_MAPPINGS as VIDEO_CAPTION_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_CAPTION_DISPLAY_MAPPINGS

# 合并节点映射
NODE_CLASS_MAPPINGS.update(IMAGE_CAPTION_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_CAPTION_DISPLAY_MAPPINGS)
NODE_CLASS_MAPPINGS.update(QA_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(QA_DISPLAY_MAPPINGS)
NODE_CLASS_MAPPINGS.update(TEXT_GEN_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(TEXT_GEN_DISPLAY_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VIDEO_CAPTION_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_CAPTION_DISPLAY_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']