# ComfyUI Qwen-VL Plugin
__version__ = "1.0.0"

# 导入节点类及显示名称
from .nodes.qwen3_vl_image_caption import NODE_CLASS_MAPPINGS as IC_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IC_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.qwen3_vl_video_caption import NODE_CLASS_MAPPINGS as VC_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VC_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.qwen3_vl_qa import NODE_CLASS_MAPPINGS as QA_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as QA_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.qwen3_vl_text_generator import NODE_CLASS_MAPPINGS as TG_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TG_NODE_DISPLAY_NAME_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {
    **IC_NODE_CLASS_MAPPINGS,
    **VC_NODE_CLASS_MAPPINGS,
    **QA_NODE_CLASS_MAPPINGS,
    **TG_NODE_CLASS_MAPPINGS,
}

# 合并所有显示名称映射
NODE_DISPLAY_NAME_MAPPINGS = {
    **IC_NODE_DISPLAY_NAME_MAPPINGS,
    **VC_NODE_DISPLAY_NAME_MAPPINGS,
    **QA_NODE_DISPLAY_NAME_MAPPINGS,
    **TG_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']